#!/usr/bin/env bash
set -o errexit

################################################################################
# things you might also need to do

# read SDL/docs/README-raspberrypi.md, notably:
# - run `sudo rpi-update`
# - set your gpu_mem=128

################################################################################
# system packages

sudo apt-get install make cmake automake g++-4.8 mercurial libglu1-mesa-dev libode-sp-dev libxi-dev build-essential mesa-common-dev libudev-dev libasound2-dev libdbus-1-dev libraspberrypi0 libraspberrypi-bin libraspberrypi-dev

################################################################################
# clean build folders

git clean -Xdf bin
git clean -Xdf debug
git clean -Xdf lib
git clean -Xdf include
git clean -Xdf release
git clean -Xdf share

################################################################################
# SDL

./script/setup_sdl

################################################################################
# SDL_image

./script_setup_sdl_image

################################################################################
# cmake

cd debug
cmake .
cd ..

cd release
cmake .
cd ..
