#!/usr/bin/env bash
set -o errexit

################################################################################
# SDL

hg clone http://hg.libsdl.org/SDL || true
cd SDL
hg pull http://hg.libsdl.org/SDL
hg update
./configure --prefix="$PWD/.." --enable-static --disable-shared --host=arm-raspberry-linux-gnueabihf --target=arm-raspberry-linux-gnueabihf --disable-video-x11
make
make install
cd ..
