#!/usr/bin/env bash
set -o errexit

################################################################################
# SDL_image

hg clone http://hg.libsdl.org/SDL_image || true
cd SDL_image
hg pull http://hg.libsdl.org/SDL_image
hg update
./autogen.sh
./configure --prefix="$PWD/.." --enable-static --disable-shared --enable-png-shared
make -j8
make install
cd ..
