#!/usr/bin/env bash
# script to run after initially cloning crag or after downloading latest ADK/NDK
# (into dl folder)
set -o errexit

# cd crag/android
cd "$( dirname "${BASH_SOURCE[0]}" )"

script/setup_pkg
script/setup_adk
script/setup_ndk
script/setup_sdl
script/setup_sdl_image
script/setup_ode
script/setup_project
