#!/bin/sh
ln -s ../../dependencies/SDL2 jni/SDL
cd ../dependencies/ode
#./bootstrap
sh autogen.sh
./configure --host=arm-linux --enable-double-precision=no --disable-demos --disable-asserts --disable-libccd
cd ../../android
