/*
 *  form/SceneThread.h
 *  Crag
 *
 *  Created by John on 10/12/09.
 *  Copyright 2009, 2010 John McFarlane. All rights reserved.
 *  This program is distributed under the terms of the GNU General Public License.
 *
 */

#pragma once

#include "Mesh.h"
#include "Scene.h"

#include "sys/Semaphore.h"
#include "sys/Thread.h"

#include "glpp/glpp.h"

#include "sys/App.h"

#include "core/double_buffer.h"


namespace sim
{
	class Observer;
}


namespace form
{
	
	// The scene is the workhorse of the formation system. 
	// SceneThread provides a thread-safe interface to the rest of the system.
	// Optionally, it can also run the scene without multithreading.
	class SceneThread
	{
		OBJECT_NO_COPY (SceneThread);
		
	public:
		SceneThread(FormationSet const & _formations, sim::Observer const & _observer, bool _threaded);
		
#if VERIFY
		void Verify() const;
#endif
		DUMP_OPERATOR_FRIEND_DECLARATION(SceneThread);
		
		void Launch();
		void ToggleSuspended();
		void Quit();
		
		//int GetTargetNumNodes() const;
		void SetFrameRatio(float ratio);

		void Tick();
		void ForEachFormation(FormationFunctor & f) const;
		bool PollMesh(MeshBufferObject & mbo);
		void ResetOrigin();
		void ToggleFlatShaded();
		
		bool IsOriginOk() const;
	private:
		bool IsResetting() const;
		bool IsGrowing() const;

		Scene & GetActiveScene();
		Scene const & GetActiveScene() const;

		Scene & GetVisibleScene();
		Scene const & GetVisibleScene() const;
		
		void Run();	// Called when thread is launched and runs the loop.
		void TickThread();
		void TickActiveScene();

		void BeginReset();
		void EndReset();

		void AdjustNumQuaterna();
		static int CalculateFrameRateDirectedTargetNumQuaterna(int current_num_quaterna, float frame_ratio);
		static int CalculateMeshGenerationDirectedTargetNumQuaterna(int current_num_quaterna, float mesh_generation_period);
		
		void GenerateMesh();
		
		bool IsMainThread() const;
		bool IsSceneThread() const;
		
		// The front scene is always the one being displayed and is usually the 'active' scene.
		// During an origin reset, the back scene is the active one.
		// It's the active scene which is reshaped for LODding purposes (churned).
		core::double_buffer<Scene> scenes;
		bool is_in_reset_mode;	// the scene is being regenerated following an origin reset
		
		int num_nodes;
		float frame_ratio;	// ~ (actual framerate / ideal framerate)
		double scene_tick_period;
		
		FormationSet const & formations;		
		sim::Observer const & observer;
		
		bool threaded;	// If false, object still does the same work, only on the main thread.
		bool reset_origin_flag;	// When set, tells thread to generate a new scene with a new origin.
		bool suspend_flag;
		bool quit_flag;
		
		// The mesh is the client-side arrays of verts and indices
		// that are generated by the scenes
		// and get passed to the VBOs.
		Mesh mesh;
		sim::Vector3 mesh_origin;
		sys::Semaphore mesh_semaphore;
		bool mesh_updated;
		sys::TimeType mesh_generation_time;
		double mesh_generation_period;

		typedef sys::Thread<SceneThread, & SceneThread::Run> Thread;
		Thread * thread;
	};
}

