#!/bin/sh

cd dependencies

# ODE
./fetch_ode

# SDL
curl http://www.libsdl.org/tmp/SDL-2.0.0-7602.tar.gz > SDL-2.0.0-7602.tar.gz
gunzip SDL-2.0.0-7602.tar.gz
tar -xf SDL-2.0.0-7602.tar
rm SDL-2.0.0-7602.tar
rm -rf SDL
mv SDL-2.0.0-7602 SDL

./build_ode
./build_sdl

cd ..
