/*
 *  form/SceneThread.h
 *  Crag
 *
 *  Created by John on 10/12/09.
 *  Copyright 2009, 2010 John McFarlane. All rights reserved.
 *  This program is distributed under the terms of the GNU General Public License.
 *
 */

#pragma once

#include "Mesh.h"
#include "Scene.h"

#include "core/Mutex.h"
#include "core/Thread.h"

#include "glpp/glpp.h"

#include "app/App.h"


namespace sim
{
	class Observer;
}


namespace form
{
	// The scene is the workhorse of the formation system. 
	// SceneThread provides a thread-safe interface to the rest of the system.
	// Optionally, it can also run the scene without multithreading.
	// TODO: Overloaded meaning; this isn't really a thread.
	class SceneThread
	{
	public:
		SceneThread(FormationSet const & _formations, sim::Observer const & _observer, bool _threaded);
		
#if VERIFY
		void Verify() const;
#endif
		DUMP_OPERATOR_FRIEND_DECLARATION(SceneThread);
		
		void Launch();
		void Quit();
		
		//int GetTargetNumNodes() const;
		void SetFrameRatio(float ratio);

		int GetNumQuaternaAvailable() const;
		
		void Tick();
		bool PollMesh(form::MeshBufferObject & mbo, sim::Vector3 & mesh_origin);
		void ResetOrigin();
		bool PostResetFreeze() const;
		
		bool OutOfRange() const;
		
	private:
		static void ThreadFunc(SceneThread * scene_thread);
		void Run();	// Called when thread is launched and runs the loop.
		void ThreadTick();
		void AdjustNumQuaterna();
		bool GenerateMesh();
		
		bool IsMainThread() const;
		bool IsSceneThread() const;

		Scene scene;
		int num_nodes;
		float frame_ratio;
		core::Mutex scene_mutex;
		
		FormationSet const & formations;		
		sim::Observer const & observer;
		
		bool threaded;	// If false, object still does the same work, only on the main thread.
		bool reset_origin_flag;	// When set, a mesh is generated (flushed) and the origin/scene is reset.
		bool suspend_flag;
		bool quit_flag;
		
		app::TimeType origin_reset_time;

		// The mesh is the client-side arrays of verts and indices
		// that are generated by the scenes
		// and get passed to the VBOs.
		form::Mesh mesh;
		core::Mutex mesh_mutex;
		bool mesh_updated;
		app::TimeType mesh_generation_time;
		float mesh_generation_period;

		core::Thread * thread;
	};
}

