#!/usr/bin/env bash
set -o errexit

# cd crag/linux
cd "$( dirname "${BASH_SOURCE[0]}" )"/..

################################################################################
# SDL

hg clone http://hg.libsdl.org/SDL || true
cd SDL
hg pull http://hg.libsdl.org/SDL
hg update
./configure --prefix="$PWD/.." --enable-static --disable-shared $@
make
make install
cd ..
