#!/usr/bin/env bash
set -o errexit

# cd crag/linux
cd "$( dirname "${BASH_SOURCE[0]}" )"/..

################################################################################
# SDL_image

hg clone http://hg.libsdl.org/SDL_image || true
cd SDL_image
hg pull http://hg.libsdl.org/SDL_image
hg update
./autogen.sh
./configure --prefix="$PWD/.." --enable-static --disable-shared --enable-png-shared
make
make install
cd ..
