#!/usr/bin/env bash
# Script to download and configure ODE for use by Crag in Android builds
set -e

#frequently fails
hg clone https://bitbucket.org/odedevs/ode || true
cd ode
hg pull https://bitbucket.org/odedevs/ode
hg update

./bootstrap
export CFLAGS="-fno-exceptions -fno-rtti -O3"
export CXXFLAGS="-fno-exceptions -fno-rtti -O3"
./configure --host=arm-linux --enable-single-precision --disable-demos --disable-asserts --disable-libccd

cd ..
