#!/usr/bin/env bash
set -o errexit

# ODE

cd jni

#frequently fails
hg clone https://bitbucket.org/odedevs/ode || true
cd ode
hg pull https://bitbucket.org/odedevs/ode
hg update

./bootstrap
CFLAGS="-fno-exceptions -fno-rtti -O3" CXXFLAGS="-fno-exceptions -fno-rtti -O3" ./configure --host=arm-linux --enable-single-precision --disable-demos --disable-asserts --disable-libccd 

cd ../..
