#!/usr/bin/env bash
set -o errexit

# extract native development kits

mkdir -p android-ndk
rm -rf android-ndk/*

cd dl
chmod +x android-ndk*.bin
./android-ndk*.bin
mv -u android-ndk*/* ../android-ndk
cd ..
