#!/usr/bin/env bash
set -e

################################################################################
# clean build folders

# cd crag/linux
cd "$( dirname "${BASH_SOURCE[0]}" )"

git clean -Xdf bin
git clean -Xdf include
git clean -Xdf lib
git clean -Xdf SDL
git clean -Xdf SDL_image
git clean -Xdf share
