#!/usr/bin/env bash
# To be run from debug or release subdirectories
set -o errexit

if [ "$#" -lt 2 ]
then
	echo "<num-cores> (release|debug) [<crag-parameter> ...]"
	exit 1
fi

JOBS="-j$1"
FOLDER="$2"
shift 2

rm core || true
make -C "$FOLDER" "$JOBS" crag&&"$FOLDER"/bin/crag $@||./bt "$FOLDER"
