#!/usr/bin/env bash
set -e

# cd crag/linux
cd "$( dirname "${BASH_SOURCE[0]}" )"

sudo apt-get install make cmake automake g++-4.8 mercurial libglu1-mesa-dev libode-sp-dev libxi-dev build-essential libpng12-dev

################################################################################
# SDL

./script/setup_sdl

################################################################################
# SDL_image

./script/setup_sdl_image
