#!/usr/bin/env bash
set -o errexit

sudo apt-get install make cmake automake g++-4.8 mercurial libglu1-mesa-dev libode-sp-dev libxi-dev build-essential libpng12-dev

################################################################################
# clean build folders

git clean -Xdf bin
git clean -Xdf debug
git clean -Xdf lib
git clean -Xdf include
git clean -Xdf release
git clean -Xdf share

################################################################################
# SDL

hg clone http://hg.libsdl.org/SDL || true
cd SDL
hg pull http://hg.libsdl.org/SDL
hg update
./configure --prefix="$PWD/.." --enable-static --disable-shared
make -j8
make install
cd ..

################################################################################
# SDL_image

hg clone http://hg.libsdl.org/SDL_image || true
cd SDL_image
hg pull http://hg.libsdl.org/SDL_image
hg update
./autogen.sh
./configure --prefix="$PWD/.." --enable-static --disable-shared --enable-png-shared
make -j8
make install
cd ..

################################################################################
# cmake

cd debug
cmake .
cd ..

cd release
cmake .
cd ..
