macro(source_group_by_folder SOURCES)
  set(SOURCE_GROUP_DELIMITER "/")
  set(LAST_DIR "")
  set(FILES "")
  foreach(file ${SOURCES})
    get_filename_component(DIR "${file}" PATH)
    if (NOT "${DIR}" STREQUAL "${LAST_DIR}")
      if (FILES)
        SOURCE_GROUP("${LAST_DIR}" FILES ${FILES})
      endif (FILES)
      set(FILES "")
    endif (NOT "${DIR}" STREQUAL "${LAST_DIR}")
    set(FILES ${FILES} ${file})
    set(LAST_DIR "${DIR}")
  endforeach(file)
  if (FILES)
    source_group("${LAST_DIR}" FILES ${FILES})
  endif (FILES)
endmacro(source_group_by_folder)

macro(populate_target SOURCE_DIR)
	file(GLOB_RECURSE SOURCES "${SOURCE_IDR}")
	source_group_by_folder("${SOURCES}")
endmacro(populate_target)
